networks:
  gitea:
    driver: bridge

services:
  server:
    image: gitea/gitea:latest
    container_name: atomicqms
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: unless-stopped
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3001:3000"
      - "222:22"

  runner:
    image: gitea/act_runner:latest
    container_name: atomicqms-runner
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - gitea
    volumes:
      - ./runner-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GITEA_INSTANCE_URL=http://server:3000
      - GITEA_RUNNER_REGISTRATION_TOKEN=${RUNNER_TOKEN:-}
      - GITEA_RUNNER_NAME=atomicqms-runner-1
      # Global Claude Code credentials (available to all repositories)
      # Set these in .env file to avoid configuring per-repository
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - CLAUDE_CODE_OAUTH_TOKEN=${CLAUDE_CODE_OAUTH_TOKEN:-}

  auto-init:
    build: ./auto-init-service
    container_name: ${ATOMICQMS_AUTO_INIT_CONTAINER:-atomicqms-auto-init}
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - gitea
    volumes:
      - ./gitea/git:/data/git:rw
    environment:
      - GIT_USER_NAME=${AUTO_INIT_GIT_USER_NAME:-AtomicQMS Auto-Init}
      - GIT_USER_EMAIL=${AUTO_INIT_GIT_USER_EMAIL:-autoinit@atomicqms.local}
      - REPO_ROOT=/data/git/repositories
      - CHECK_INTERVAL=${AUTO_INIT_CHECK_INTERVAL:-300}
    profiles:
      - auto-init
