# Gitea Actions Runner Configuration
# This file configures how the act_runner spawns job containers

log:
  level: info

runner:
  # Fetch new jobs every 2 seconds
  fetch_timeout: 2s
  fetch_interval: 2s

  # Timeout for a single job
  timeout: 3h

container:
  # Network configuration for job containers
  # Job containers run in isolation
  # Gitea is accessed via host.docker.internal:3001 (see GITEA_INSTANCE_URL in docker-compose.yml)
  network: ""

  # Enable privileged mode if needed for Docker-in-Docker
  privileged: false

  # Container options
  options: ""

  # Mount docker socket for Docker-in-Docker workflows
  # workdir_parent: ""

host:
  # Use the docker socket from the host
  workdir_parent: ""
